/* =============================================================
   Province / Region -> City-Municipality dependent dropdown data.
   City is THE dealer-territory key, so it is always a dropdown,
   never free text. Replace with the full PSGC table on the
   server build; this covers every region and all dealer-relevant
   cities for launch.
   ============================================================= */
window.XPENG_GEO = {
  "Metro Manila (NCR)":["Caloocan","Las Piñas","Makati","Malabon","Mandaluyong","Manila","Marikina","Muntinlupa","Navotas","Parañaque","Pasay","Pasig","Pateros","Quezon City","San Juan","Taguig","Valenzuela"],
  "Abra":["Bangued","Lagangilang","Tayum"],
  "Agusan del Norte":["Butuan","Cabadbaran","Nasipit"],
  "Agusan del Sur":["Bayugan","Prosperidad","San Francisco"],
  "Aklan":["Kalibo","Malay (Boracay)","Banga"],
  "Albay":["Legazpi","Ligao","Tabaco","Daraga"],
  "Antique":["San Jose de Buenavista","Culasi","Sibalom"],
  "Apayao":["Luna","Kabugao"],
  "Aurora":["Baler","Dipaculao","Maria Aurora"],
  "Basilan":["Isabela City","Lamitan"],
  "Bataan":["Balanga","Dinalupihan","Hermosa","Mariveles","Orani"],
  "Batanes":["Basco"],
  "Batangas":["Batangas City","Lipa","Tanauan","Santo Tomas","Bauan","Nasugbu","Calaca","Malvar"],
  "Benguet":["Baguio","La Trinidad","Itogon","Tuba"],
  "Biliran":["Naval"],
  "Bohol":["Tagbilaran","Panglao","Ubay","Talibon"],
  "Bukidnon":["Malaybalay","Valencia","Manolo Fortich"],
  "Bulacan":["Malolos","Meycauayan","San Jose del Monte","Marilao","Bocaue","Balagtas","Plaridel","Baliuag","Santa Maria","Pulilan","Hagonoy"],
  "Cagayan":["Tuguegarao","Aparri","Solana"],
  "Camarines Norte":["Daet","Labo"],
  "Camarines Sur":["Naga","Iriga","Pili","Calabanga"],
  "Camiguin":["Mambajao"],
  "Capiz":["Roxas City","Panay","Pontevedra"],
  "Catanduanes":["Virac"],
  "Cavite":["Bacoor","Imus","Dasmariñas","General Trias","Trece Martires","Tagaytay","Silang","Carmona","Kawit","Naic","Tanza","Cavite City"],
  "Cebu":["Cebu City","Mandaue","Lapu-Lapu","Talisay","Consolacion","Minglanilla","Naga","Danao","Carcar","Toledo","Liloan","Cordova"],
  "Cotabato (North)":["Kidapawan","Midsayap","Kabacan"],
  "Davao de Oro":["Nabunturan","Maco","Monkayo"],
  "Davao del Norte":["Tagum","Panabo","Santo Tomas","Carmen"],
  "Davao del Sur":["Davao City","Digos","Santa Cruz"],
  "Davao Occidental":["Malita"],
  "Davao Oriental":["Mati","Banaybanay"],
  "Dinagat Islands":["San Jose"],
  "Eastern Samar":["Borongan","Guiuan"],
  "Guimaras":["Jordan","Buenavista"],
  "Ifugao":["Lagawe","Banaue"],
  "Ilocos Norte":["Laoag","Batac","San Nicolas","Paoay"],
  "Ilocos Sur":["Vigan","Candon","Narvacan"],
  "Iloilo":["Iloilo City","Passi","Oton","Pavia","Santa Barbara","Dumangas"],
  "Isabela":["Ilagan","Cauayan","Santiago","Roxas"],
  "Kalinga":["Tabuk"],
  "La Union":["San Fernando","Agoo","Bauang","Rosario"],
  "Laguna":["Santa Rosa","Biñan","San Pedro","Calamba","Cabuyao","San Pablo","Los Baños","Sta. Cruz","Alaminos"],
  "Lanao del Norte":["Iligan","Tubod"],
  "Lanao del Sur":["Marawi","Malabang"],
  "Leyte":["Tacloban","Ormoc","Baybay","Palo"],
  "Maguindanao del Norte":["Datu Odin Sinsuat"],
  "Maguindanao del Sur":["Buluan"],
  "Marinduque":["Boac"],
  "Masbate":["Masbate City"],
  "Misamis Occidental":["Oroquieta","Ozamiz","Tangub"],
  "Misamis Oriental":["Cagayan de Oro","Gingoog","El Salvador","Opol"],
  "Mountain Province":["Bontoc","Sagada"],
  "Negros Occidental":["Bacolod","Talisay","Silay","Bago","Kabankalan","San Carlos","Victorias"],
  "Negros Oriental":["Dumaguete","Bais","Tanjay","Valencia"],
  "Northern Samar":["Catarman","Laoang"],
  "Nueva Ecija":["Cabanatuan","San Jose City","Gapan","Palayan","Santa Rosa","Talavera"],
  "Nueva Vizcaya":["Bayombong","Solano"],
  "Occidental Mindoro":["Mamburao","San Jose"],
  "Oriental Mindoro":["Calapan","Puerto Galera","Pinamalayan"],
  "Palawan":["Puerto Princesa","El Nido","Coron","Roxas"],
  "Pampanga":["Angeles","San Fernando","Clark Freeport","Mabalacat","Mexico","Apalit","Guagua","Porac"],
  "Pangasinan":["Dagupan","San Carlos","Urdaneta","Alaminos","Lingayen","Rosales"],
  "Quezon":["Lucena","Tayabas","Candelaria","Sariaya","Lucban"],
  "Quirino":["Cabarroguis"],
  "Rizal":["Antipolo","Cainta","Taytay","Binangonan","Rodriguez","San Mateo","Angono","Tanay"],
  "Romblon":["Romblon","Odiongan"],
  "Samar (Western)":["Catbalogan","Calbayog"],
  "Sarangani":["Alabel","Glan"],
  "Siquijor":["Siquijor"],
  "Sorsogon":["Sorsogon City","Bulan","Gubat"],
  "South Cotabato":["General Santos","Koronadal","Polomolok"],
  "Southern Leyte":["Maasin"],
  "Sultan Kudarat":["Tacurong","Isulan"],
  "Sulu":["Jolo"],
  "Surigao del Norte":["Surigao City","Dapa (Siargao)"],
  "Surigao del Sur":["Bislig","Tandag"],
  "Tarlac":["Tarlac City","Concepcion","Paniqui","Capas"],
  "Tawi-Tawi":["Bongao"],
  "Zambales":["Olongapo","Iba","Subic","Castillejos"],
  "Zamboanga del Norte":["Dipolog","Dapitan"],
  "Zamboanga del Sur":["Pagadian","Zamboanga City"],
  "Zamboanga Sibugay":["Ipil"],
  "Outside the Philippines":["Overseas / OFW"]
};

/* "What do you drive today?" — top PH brands (Step 2 conquest signal) */
window.XPENG_BRANDS = ["Toyota","Mitsubishi","Nissan","Honda","Ford","Hyundai","Kia","Suzuki","Isuzu","Chevrolet","Mazda","MG","Geely","Chery","BYD","Changan","Foton","Subaru","Volkswagen","BMW","Mercedes-Benz","Lexus","Other brand","No car yet"];
